package com.vigilx.apisecurity.inventory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

/**
 * Automates brief Phase 6/34's "revalidate the existing MissingApiRegistry": given a fresh
 * {@link com.vigilx.apisecurity.inventory.ApiComparisonService.ComparisonResult}, this
 * <strong>rewrites the actual source file</strong> ({@code src/test/resources/apisecurity/missing-apis.json})
 * rather than requiring a one-off script - real, repeatable code, run as part of the pipeline.
 *
 * <p>Two things happen, both driven only by real comparison evidence:
 * <ul>
 *   <li><strong>Remove</strong> any registry entry ApiMonitor now captures (comparisonKey matches an
 *       {@link ApiComparisonService.ComparisonResult#monitorApis()} entry) - it is a stale duplicate
 *       and Phase 6 explicitly says it must not stay in the registry.</li>
 *   <li><strong>Add</strong> any {@link ApiComparisonService.ComparisonResult#missingFromMonitor()}
 *       entry not already present - never anything else, never a raw HAR entry the comparison hasn't
 *       actually confirmed missing.</li>
 * </ul>
 *
 * <p>The registry stays git-trackable and human-inspectable: this only ever adds/removes JSON
 * objects in the existing file, preserving its {@code _readme} block and every other field.
 */
public final class MissingApiRegistryUpdater {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private MissingApiRegistryUpdater() {
    }

    public static final class RegenerationResult {
        public final List<String> added = new ArrayList<>();
        public final List<String> removed = new ArrayList<>();
        public int unchanged;
    }

    public static RegenerationResult regenerate(ApiComparisonService.ComparisonResult comparison, Path registryFile)
            throws IOException {
        RegenerationResult result = new RegenerationResult();

        ObjectNode root = readOrCreate(registryFile);
        ArrayNode apis = root.has("apis") && root.get("apis").isArray()
                ? (ArrayNode) root.get("apis") : root.putArray("apis");

        Set<String> monitorKeys = keysOf(comparison.monitorApis());

        // Remove stale entries: ApiMonitor now captures them.
        ArrayNode kept = MAPPER.createArrayNode();
        for (JsonNode entry : apis) {
            String key = comparisonKeyOf(entry);
            if (monitorKeys.contains(key)) {
                result.removed.add(key);
            } else {
                kept.add(entry);
                result.unchanged++;
            }
        }

        // Add newly confirmed-missing entries not already present.
        Set<String> existingKeys = new HashSet<>();
        for (JsonNode entry : kept) {
            existingKeys.add(comparisonKeyOf(entry));
        }
        for (ApiDefinition missing : comparison.missingFromMonitor()) {
            if (existingKeys.contains(missing.comparisonKey())) {
                continue;
            }
            kept.add(toRegistryEntry(missing));
            result.added.add(missing.comparisonKey());
        }

        root.set("apis", kept);
        Files.createDirectories(registryFile.toAbsolutePath().getParent());
        MAPPER.writerWithDefaultPrettyPrinter().writeValue(registryFile.toFile(), root);

        return result;
    }

    private static ObjectNode readOrCreate(Path registryFile) throws IOException {
        if (Files.exists(registryFile)) {
            JsonNode existing = MAPPER.readTree(registryFile.toFile());
            if (existing.isObject()) {
                return (ObjectNode) existing;
            }
        }
        ObjectNode root = MAPPER.createObjectNode();
        ArrayNode readme = root.putArray("_readme");
        readme.add("Only ever contains APIs ApiComparisonService has confirmed missing from ApiMonitor's "
                + "real capture. Regenerated by MissingApiRegistryUpdater - manual edits to individual "
                + "entries' \"reason\"/\"expectedStatus\" survive a regeneration; entries ApiMonitor now "
                + "captures are automatically removed.");
        root.putArray("apis");
        return root;
    }

    private static ObjectNode toRegistryEntry(ApiDefinition missing) {
        ObjectNode entry = MAPPER.createObjectNode();
        entry.put("method", missing.method());
        entry.put("host", missing.host());
        entry.put("path", missing.samplePath());
        entry.put("query", missing.sampleQuery() == null ? "" : missing.sampleQuery());
        entry.put("expectedStatus", missing.sampleStatus());
        entry.put("normalizedPath", missing.normalizedPath());
        if (missing.authObservedInSample() != null) {
            entry.put("authObservedInSample", missing.authObservedInSample());
        } else {
            entry.putNull("authObservedInSample");
        }
        if (missing.hasSampleRequestBody()) {
            entry.put("sampleRequestBody", missing.sampleRequestBody());
        } else {
            entry.putNull("sampleRequestBody");
        }
        entry.put("reason", "Confirmed missing from ApiMonitor capture by ApiComparisonService on "
                + LocalDate.now());
        return entry;
    }

    private static String comparisonKeyOf(JsonNode entry) {
        String method = entry.path("method").asText("").toUpperCase(java.util.Locale.ROOT);
        String host = entry.path("host").asText("");
        String path = entry.path("normalizedPath").asText(
                ApiNormalizer.normalizePath(entry.path("path").asText("/")));
        return method + " " + host + path;
    }

    private static Set<String> keysOf(List<ApiDefinition> definitions) {
        Set<String> keys = new HashSet<>();
        for (ApiDefinition definition : definitions) {
            keys.add(definition.comparisonKey());
        }
        return keys;
    }
}
